export enum TrackingPhase {
  WAITING_FOR_ANSWER       = 'WAITING_FOR_ANSWER',
  EP_NOT_RESPONDING        = 'EP_NOT_RESPONDING',
  EXPLAINING_AIESEC        = 'EXPLAINING_AIESEC',
  LOOKING_FOR_OPPORTUNITIES = 'LOOKING_FOR_OPPORTUNITIES',
  HAVING_INTERVIEW         = 'HAVING_INTERVIEW',
  WILL_SIGN_CONTRACT       = 'WILL_SIGN_CONTRACT',
  CONTRACT_SIGNED          = 'CONTRACT_SIGNED',
  WAITING_FOR_CV           = 'WAITING_FOR_CV',
  NOT_INTERESTED_ANYMORE   = 'NOT_INTERESTED_ANYMORE',
}
